@startuml ObjectCreation
title Sequence Diagram - Object Creation
autonumber

actor Client
participant "player_create /\nhouse_create /\ntree_create" as Factory
participant GameEntity
participant GameObject
participant CollisionHeap
participant Collision
participant PhysicsBody

Client -> Factory : create entity(heap, x, y, z, on_collision)
Factory -> GameEntity : game_entity_create(name, initial_capacity)
create GameEntity
GameEntity --> Factory : entity

Factory -> GameEntity : game_entity_set_on_collision(callback)
Factory -> GameEntity : game_entity_set_position(x, y, z)
GameEntity -> GameEntity : game_entity_sync_parts()

Factory -> GameEntity : game_entity_add_primitive(part_name, primitive_type)
GameEntity -> GameObject : game_object_create(part_name, primitive_type)
create GameObject
GameObject --> GameEntity : part
GameEntity -> GameObject : game_object_set_owner(entity, bridge_callback)
GameEntity -> GameObject : game_object_sync_world(entity.x, entity.y, entity.z)
GameEntity --> Factory : part

Factory -> GameObject : set local transform / size / radius / color
Factory -> GameEntity : game_entity_attach_part_collider(part, heap, class, shape)
GameEntity -> GameObject : game_object_attach_collider(heap, class, shape)
GameObject -> Collision : collision_create(part, class, shape)
create Collision
Collision --> GameObject : collider
GameObject -> Collision : collision_set_callback(game_object_collision_bridge)
GameObject -> CollisionHeap : collision_heap_push(collider)
CollisionHeap --> GameObject : success
GameObject --> GameEntity : attached
GameEntity -> GameObject : game_object_sync_world(entity.x, entity.y, entity.z)

alt entity uses physics
    Factory -> GameEntity : game_entity_enable_physics(mass, damping)
    GameEntity -> PhysicsBody : physics_body_init(mass, damping)
end

Factory -> GameEntity : game_entity_sync_parts()
Factory --> Client : GameEntity*
@enduml
